name: Hola mundo

on : [push]

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: hello mundo
      run: echo "hello mundo"
    
    - name: touch file
      run: touch hola.txt
    
    - name: Set Text
      run: echo "hola mundo" >> hola.txt

    - name: Show file
      run: cat hola.txt
  
  other:
    runs-on: ubuntu-latest
    steps:
    - name: List files
      run: ls