name: Hola mundo

on : [push]

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: hello mundo
      run: echo "hello mundo"
  
  other:
    runs-on: ubuntu-latest
    steps:
    - name: List files
      run: ls